# .github/dependabot.yml
# A minimal Dependabot configuration for Flutter/Dart (pub)

version: 2
updates:
  - package-ecosystem: "pub"  # Use "pub" for Dart/Flutter packages
    directory: "/"           # Location of your pubspec.yaml file
    schedule:
      interval: "daily"
      time: "07:55"          # Optional: Specify a time (UTC)
